# Generated by Django 4.0.5 on 2022-07-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('password', models.TextField(default='', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], default='employee', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
